_target_: src.models.DANN_module.GAN

latent_dim: 100
lr: 1e-2
weight_decay: 2.5e-5
optimizer: sgd
batch_size: 64
use_tgt_val: true
iterations: false
num_workers: 16
alpha: 10
gamma: 10
beta: 0.75
lr_schedule: true


feature_extractor:
  _target_: src.models.components.generator.Generator
  channels: 1
  height: 28
  width: 28

classifier:
  _target_: src.models.components.discriminator.Discriminator
  channels: 1
  height: 28
  width: 28

discriminator:
  _target_: src.models.components.discriminator.Discriminator
  channels: 1
  height: 28
  width: 28