_target_: src.models.GAN_module.GAN

latent_dim: 100
lr: 0.0002
b1: 0.5
b2: 0.999

generator:
  _target_: src.models.components.generator.Generator
  channels: 1
  height: 28
  width: 28

discriminator:
  _target_: src.models.components.discriminator.Discriminator
  channels: 1
  height: 28
  width: 28
