_target_: src.models.vgg_module.VGGModule

optimizer:
  _target_: torch.optim.Adam
  _partial_: true
  lr: 0.0001
  weight_decay: 0.0

net:
  _target_: src.models.components.vgg16_cnn.VGG16
  input_size: 3
  conv1_size: 64
  conv2_size: 128
  conv3_size: 256
  conv4_size: 512
  lin1_size: 4096
  output_size: 1000
  kernel_size: 3
  stride: 1
  padding: 1
  maxpool_kernel_size: 2
  maxpool_stride: 2
  dropout: 0.5